server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://db:5432/biblioteca
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    org.springframework: INFO
